default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  primary:
    <<: *default
  queue:
    <<: *default
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
  queue:
    <<: *default
    migrations_paths: db/queue_migrate

production:
  primary:
    <<: *default
  queue:
    <<: *default
    migrations_paths: db/queue_migrate
